### ISSUE TITLE
打开时闪退

### ISSUE THREAD

**Issue by lsbnbdz** [azhu003/localsend-harmony#3]
您好，我已经编译成功，但是安装之后，打开会闪退，请求您的协助
```shell
Device info:HUAWEI Mate 60 Pro
Build info:ALN-AL00 5.0.0.113(SP2C00E110R4P22)
Fingerprint:6ac0a02f4211c002ea742e391ece9c5386f356facf1488bea4a923c542df1540
Module name:com.jerry.localsend
Version:1.0.0
VersionCode:1000000
PreInstalled:No
Foreground:No
Pid:65383
Uid:20020255
Reason:ReferenceError
Error name:ReferenceError
Error message:cannot find record '&rdbplus/src/main/ets/BaseMapper&1.0.5', please check the request path.'/data/storage/el1/bundle/entry/ets/modules.abc'.
Stacktrace:
SourceMap is not initialized yet 
#00 pc 00000000006d67cc /system/lib64/platformsdk/libark_jsruntime.so(0a5e5a08ab1e8b1f274b227e2dc8bb96)
```

**Comment by azhu003** [comment]
rdbplus这个插件版本依赖错了吧，改成1.0.6试试

**Comment by lsbnbdz** [comment]
> rdbplus这个插件版本依赖错了吧，改成1.0.6试试

您好，感谢您的回答，但我检查了工程文件，所有依赖版本并未做更改
![image](https://github.com/user-attachments/assets/528c745a-6041-4a4b-a203-76ce888667b4)
都是导入工程后，通过IDE自动获取的，并分别更试了api版本12和13发现都不可以，但有的群友却可以成功编译并完成启动，这让人很抓狂。

**Comment by azhu003** [comment]
检查下这里下载的插件有问题没
<img width="359" alt="image" src="https://github.com/user-attachments/assets/0af072d6-eb7f-4d23-b13c-2207bebbb98f" />

**Comment by lsbnbdz** [comment]
> 检查下这里下载的插件有问题没 <img alt="image" width="359" src="https://private-user-images.githubusercontent.com/29949867/396843363-0af072d6-eb7f-4d23-b13c-2207bebbb98f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTQ5MDUsIm5iZiI6MTczNDUxNDYwNSwicGF0aCI6Ii8yOTk0OTg2Ny8zOTY4NDMzNjMtMGFmMDcyZDYtZWI3Zi00ZDIzLWIxM2MtMjIwN2JlYmJiOThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYTFhYjFjYzZkMGEyNDYwYTU2ZGI5NTJmNzVjOTkzYTZlMDU5MjczZDU2OWJhNzRhNDZhY2MyZmVhODJiY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3ZpB_Z2dEV00eBKCLUsoMclL0n1HKNSx_4qYaeCy-uI">

你好，我发现了问题，他报错是
```shell
Error message:cannot find record '&rdbplus/src/main/ets/BaseMapper&1.0.5', please check the request path.'/data/storage/el1/bundle/entry/ets/modules.abc'.
```
也就是在modules.abc中无法找到`&rdbplus/src/main/ets/BaseMapper&1.0.5`记录，既然咱们使用的是1.0.6版本的rdbplus，那使用的类也应该是1.0.6版本的，所以我打开了modules.abc文件，把所有的1.0.5都改成了1.0.6，然后发现，竟然可以使用了。但是我无法理解的是IDE自动从三方库获取的rdbplus组件，为什么modules.abc中会有版本号的错误

**Comment by songxing10000** [comment]
/Users/edy/localsend-harmony/entry/build/default/intermediates/loader_out/default/ets/modules.abc

**Comment by FiveHair** [comment]
我也是新环境 报相同的错误
![image](https://github.com/user-attachments/assets/19cf2211-16a0-4bf0-b2e6-0a32fe06fb3c)
好像是rdbplus的问题？

**Comment by azhu003** [comment]
> 我也是新环境 报相同的错误 ![image](https://private-user-images.githubusercontent.com/16514929/397369989-19cf2211-16a0-4bf0-b2e6-0a32fe06fb3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTIwODcsIm5iZiI6MTczNDYxMTc4NywicGF0aCI6Ii8xNjUxNDkyOS8zOTczNjk5ODktMTljZjIyMTEtMTZhMC00YmYwLWIyZTYtMGEzMmZlMDZmYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMmFhNjMzNzgwZWFjNWUzYmQwYTBiZDM5OGJlZGQ0Nzg2YzA4YTc3ZmNmNzZjNTU0NjNhNTBhMmY4OWU4ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.re7C3477borhn95pxWJ56V74qOpfAgEr_dfy76CZIkQ) 好像是rdbplus的问题？

不知道IDE为什么会下载1.0.5版本的rdbplus，回头我再看看啥原因

**Comment by FiveHair** [comment]
> > 我也是新环境 报相同的错误 ![image](https://private-user-images.githubusercontent.com/16514929/397369989-19cf2211-16a0-4bf0-b2e6-0a32fe06fb3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTIwODcsIm5iZiI6MTczNDYxMTc4NywicGF0aCI6Ii8xNjUxNDkyOS8zOTczNjk5ODktMTljZjIyMTEtMTZhMC00YmYwLWIyZTYtMGEzMmZlMDZmYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMmFhNjMzNzgwZWFjNWUzYmQwYTBiZDM5OGJlZGQ0Nzg2YzA4YTc3ZmNmNzZjNTU0NjNhNTBhMmY4OWU4ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.re7C3477borhn95pxWJ56V74qOpfAgEr_dfy76CZIkQ) 好像是rdbplus的问题？
> 
> 不知道IDE为什么会下载1.0.5版本的rdbplus，回头我再看看啥原因

rdbplus那边也有提这个错误的https://github.com/yongoe1024/RdbPlus/issues/2

**Comment by lsbnbdz** [comment]
> 我也是新环境 报相同的错误 ![image](https://private-user-images.githubusercontent.com/16514929/397369989-19cf2211-16a0-4bf0-b2e6-0a32fe06fb3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTY4NDUsIm5iZiI6MTczNDYxNjU0NSwicGF0aCI6Ii8xNjUxNDkyOS8zOTczNjk5ODktMTljZjIyMTEtMTZhMC00YmYwLWIyZTYtMGEzMmZlMDZmYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEzNTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNTU4MjdhZmU2MWFhM2RhZDEzMGFmNTQ3MDdmZTA3YTk4YjJmOTJlNzdhMTI3MzVhODBlNzdkZWJmOWFiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7uID6okz_0L726eIAdZJkXlScc3lVvmz8YFpxlPGmRM) 好像是rdbplus的问题？

是rdbplus的问题，从三方库下载下来的har包，我解开看modules.abc里面就是有问题的，不是ide后天加工导致的版本号错误，实际上rdbplus的版本是1.0.6，只是.abc文件里的某些记录有问题
要解决问题找到`localsend-harmony\oh_modules\.ohpm\rdbplus@1.0.6\oh_modules\rdbplus\ets`目录下的module.abc文件，用记事本打开，将所有1.0.5替换成1.0.6后，即可。

**Comment by lsbnbdz** [comment]
> modules.abc这个文件在哪里啊， 我只找到了这个/Users/edy/localsend-harmony/entry/build/default/intermediates/loader_out/default/ets/modules.abc 每次编译运行，里面的修改了的1.0.6都会变成1.0.5

在`localsend-harmony`目录下，找到`\oh_modules\.ohpm\rdbplus@1.0.6\oh_modules\rdbplus\ets`目录，将module.abc文件中的1.0.5替换成1.0.6即可

**Comment by FiveHair** [comment]
> > 我也是新环境 报相同的错误 ![image](https://private-user-images.githubusercontent.com/16514929/397369989-19cf2211-16a0-4bf0-b2e6-0a32fe06fb3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTY4NDUsIm5iZiI6MTczNDYxNjU0NSwicGF0aCI6Ii8xNjUxNDkyOS8zOTczNjk5ODktMTljZjIyMTEtMTZhMC00YmYwLWIyZTYtMGEzMmZlMDZmYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEzNTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNTU4MjdhZmU2MWFhM2RhZDEzMGFmNTQ3MDdmZTA3YTk4YjJmOTJlNzdhMTI3MzVhODBlNzdkZWJmOWFiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7uID6okz_0L726eIAdZJkXlScc3lVvmz8YFpxlPGmRM) 好像是rdbplus的问题？
> 
> 是rdbplus的问题，从三方库下载下来的har包，我解开看modules.abc里面就是有问题的，不是ide后天加工导致的版本号错误，实际上rdbplus的版本是1.0.6，只是.abc文件里的某些记录有问题 要解决问题找到`localsend-harmony\oh_modules\.ohpm\rdbplus@1.0.6\oh_modules\rdbplus\ets`目录下的module.abc文件，用记事本打开，将所有1.0.5替换成1.0.6后，即可。

![image](https://github.com/user-attachments/assets/dd4c44df-db1d-4c08-a552-8185be8425b1)
放弃了 等rdbplus修吧

**Comment by yongoe1024** [comment]
尝试最新版本1.0.8，或者文件引入 https://github.com/yongoe1024/RdbPlus/releases/tag/v1.0.8  
由于未复现，怀疑ide版本差异，导致某工程配置的参数改变

**Comment by azhu003** [comment]
已修复

**Comment by songxing10000** [comment]
终于能用了
![image](https://github.com/user-attachments/assets/2d1f2dd8-3fa0-494f-aca4-1abf87e08dbe)
